<?php if ($this->getPaymentInfoEnabled()):?>
<a style="float: none;" href="#" onclick="popWin('<?php echo $this->getUrl('payitsimple/payment/help')?>', 'Tell me more', 'width=433,height=607,left=0,top=0,location=no,status=no,scrollbars=no,resizable=no'); return false;"><?php echo $this->getPaymentInfoTitle() ?></a>
<?php endif; ?>
<img style="float: right; margin-left: 10px;" src="//www.credit-card-logos.com/images/visa_credit-card-logos/visa_mastercard_2.gif"/>